[versions]
minecraft = "1.21.1"
neoForge = "21.1.210"
parchment = "2024.11.17"
modDevGradle = "2.0.86"

emi = "1.1.22+1.21.1"
jei = "19.25.0.321"

patchouli = "1.21.1-92-NEOFORGE"

# Modrinth Maven #
jade = "15.10.0+neoforge"

# Curse Maven  #
tfc = "7476548"
tfc_ie_addon = "7155223"
ie = "6733669"
kubastfca = "7142373"
firmalife = "7498010"

[libraries]
jei-common-api = { module = "mezz.jei:jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge-api = { module = "mezz.jei:jei-1.21.1-neoforge-api", version.ref = "jei" }
jei = { module = "mezz.jei:jei-1.21.1-neoforge", version.ref = "jei" }
emi = { module = "dev.emi:emi-neoforge", version.ref = "emi" }
patchouli = { module = "vazkii.patchouli:Patchouli", version.ref = "patchouli"}

# Modrinth Maven #
jade = { module = "maven.modrinth:jade", version.ref = "jade" }

# Curse Maven #
tfc = { module = "curse.maven:terrafirmacraft-302973", version.ref = "tfc" }
firmalife = { module = "curse.maven:firmalife-453394", version.ref = "firmalife" }
tfc_ie_addon = { module = "curse.maven:advanced-tfc-tech-unofficial-862559", version.ref = "tfc_ie_addon" }
ie = { module = "curse.maven:immersive-engineering-231951", version.ref = "ie" }
kubastfca = { module = "curse.maven:kubas-tfc-additions-1213369", version.ref = "kubastfca" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }

[bundles]
jei = ["jei-common-api", "jei-neoforge-api"]
